apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-manager-backend
  namespace: vm-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-manager-backend
  template:
    metadata:
      labels:
        app: vm-manager-backend
    spec:
      serviceAccountName: vm-manager-backend
      containers:
        - name: backend
          image: algertislamaj/vm-manager-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: vm-manager-postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vm-manager-backend
  namespace: vm-manager
spec:
  selector:
    app: vm-manager-backend
  ports:
    - port: 8080
      targetPort: 8080