apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-manager-backend
  namespace: vm-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-manager-secret-manager
  namespace: vm-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-manager-backend-binding
  namespace: vm-manager
subjects:
  - kind: ServiceAccount
    name: vm-manager-backend
    namespace: vm-manager
roleRef:
  kind: Role
  name: vm-manager-secret-manager
  apiGroup: rbac.authorization.k8s.io